on: issues
name: Issue triage
jobs:
  markIssuesForTriage:
    runs-on: ubuntu-latest
    steps:
    - name: Add new issue into Triage Board
      uses: alex-page/github-project-automation-plus@v0.1.1
      if: github.event.action == 'opened'
      with:
        project: OSS Board
        column:  Needs Triage
        repo-token: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
